### ISSUE TITLE
Fetching fails when there is no payload

### ISSUE THREAD

**Issue by jansi-z** [amplitude/experiment-ruby-server#10]
## Expected Behavior
- I initialize a client: `client = Experiment.new('123abc', Experiment::Config.new)`
- I initialize a user: `user = Experiment::User.new(user_id: 'foo')`
- I request the variants: `variants = client.fetch(user)`
- `variants` is defined as a hash that contains the variants for the user.

## Current Behavior

- Instead of returning the variants, I get an error: `ERROR -- : [Experiment] Fetch failed: key not found: "payload"`

## Possible Solution

I added some breakpoints to `lib/experiment/client.rb`, and I discovered that the JSON returned by the Amplitude call did not return any `payload` field. [So this bit of code fails](https://github.com/amplitude/experiment-ruby-server/blob/41f162025182c187d2be75e0e3e9eb4d642445ff/lib/experiment/client.rb#L132). One way to solve this would be to change `value.fetch('payload')` to `value.fetch('payload', nil)`. It does look like `Variant` is able to handle a `nil` payload.

## Steps to Reproduce
 

See under 'Expected Behavior'. Let me know if more information is needed.

## Environment
- SDK Version: 1.0.0.beta.3
- Language Version: 2.7.5

**Comment by qingzhuozhen** [comment]
Hi @jansi-z I just deployed the new version v1.0.0-beta.4 including the fix. Feel free to upgrade the version and let me know how that goes. Thank you.

**Comment by jansi-z** [comment]
@qingzhuozhen Wow, thanks for picking this up so fast! I'll give it a try right away.

**Comment by jansi-z** [comment]
@qingzhuozhen My issue is fixed, so I'll close this! I'm getting variants now instead of an error. Thanks again for the fast response!
