### ISSUE TITLE
Rename "Experiment" namespace

### ISSUE THREAD

**Issue by gogiel** [amplitude/experiment-ruby-server#12]
All namespaces in Ruby are global.
Current implementation uses global `Experiment` namespace.
Because `Experiment` is a common word there's quite a high chance of collision when integrating into existing application.

Additionally it's common convention to match gem name with the implemented namespace.

That's why I suggest renaming the namespace to `AmplitudeExperiment`.

If you agree with that I can help with the implementation and prepare a PR.

## Summary

Rename `Experiment` namespace to `AmplitudeExperiment`.

## Motivations

* avoid namespace collision
* follow conventions

**Comment by qingzhuozhen** [comment]
Hi @gogiel That makes sense. I will update the namespace soon.

**Comment by qingzhuozhen** [comment]
Hi @gogiel The namespace change is already made and released in v1.0.0.beta.5. Feel free to upgrade and let us know if there is any other concern. Thanks for your suggestion!
