### ISSUE TITLE
Local evaluation polling interval bug

### ISSUE THREAD

**Issue by bgiori** [amplitude/experiment-ruby-server#25]
## Expected Behavior

* polling interval should be set to the configured interval
* polling interval should be set to the correct interval

## Current Behavior

* polling interval configuration does not actually set the SDKs polling interval
* ruby sleep uses seconds, not milliseconds, poller actually waits 8 hours

## Possible Solution

* Pass configured polling interval from client to poller
* Make sure correct time unit is being used when calling sleep

**Comment by qingzhuozhen** [comment]
@bgiori Just released v1.0.0-beta.11 including the fix for this.
