### ISSUE TITLE
Add IP address to user object so geoip and user targeting works without needing MaxMind

### ISSUE THREAD

**Issue by joshunger** [amplitude/experiment-ruby-server#47]
## Summary

Would it be possible to add IP address to the user object so geoip and user targeting works correctly when retrieving variants for a new user? We'd like to avoid running MaxMind and adding logic to determine the user's location properties - City, Country , Region, DMA - before making a call to fetch variants for a new user.

## Motivations

This would be a huge benefit and not force every customer to run an up to date MaxMind.

**Comment by bgiori** [comment]
Hey @joshunger thanks for submitting this ticket!

Just to clarify, you'd like to be able to pass the user's IP address directly?

**Comment by joshunger** [comment]
👋 @bgiori yes please! We'd like the ability to pass the user's IP and _also_ have Amplitude perform the geoip resolution and save City, Country, Region, DMA to the user properties so user targeting works. Would it be possible for you to elaborate on how other customers are using location based user targeting?

**Comment by bgiori** [comment]
Assuming you're using remote evaluation, we sync the user properties stored in Amplitude for the user prior to evaluation which usually includes the location properties if the user is already known.

I admit though, if the evaluation request is for a user without existing location info, we will actually resolve the request's remote IP, which is unfortunately coming from the server rather than the actual user.

**Comment by tyiuhc** [comment]
Hi @joshunger, many thanks for your patience on this! In v1.2.5, you will be able to pass in `ip_address` as a user property such that it can be used for remote evaluation. Please let us know if there continue to be issues with targeting.

**Comment by joshunger** [comment]
@tyiuhc thank you! Does this work in https://github.com/amplitude/experiment-node-server as well? If not, can we get it fixed? 🙏

**Comment by tyiuhc** [comment]
Hi @joshunger, `ip_address` can now be passed as a user property in v1.8.1 of Experiment's Node Server SDK.
